### ISSUE TITLE
error with C3Guage hello world

### ISSUE THREAD

**Issue by MySchizoBuddy** [FrissAnalytics/shinyJsTutorials#3]
running the C3Guage("hello, world") command results in an error

```
Error in (function (name, version, src, meta = NULL, script = NULL, stylesheet = NULL,  : 
  argument "version" is missing, with no default
```

Also why does the hello world even work. Is it because of 

```
el.innerText = x.message;
```

in the C3Guage.js default template

Using Microsoft R Open 3.2.3 on windows 10
devtools 1.11.1
htmlwidgets 0.6

**Comment by erwinschuijtvlotfriss** [comment]
It looks like no version is set in the C3Gauge.yaml file for some reason. Ill have to look into this to see why this is the case.

To fix this for now you can manually add it by changing the contents of C3Gauge.yaml to:

```
dependencies:
- name: d3
  src: htmlwidgets/lib/d3
  script: ./d3.min.js
  version: 3.5.0
- name: c3
  src: htmlwidgets/lib/c3
  script: ./c3.min.js
  style: ./c3.min.css
  version: 0.4.10
```

And you are correct it indeed works because of that line. This line changes the text of the element created by the widget with the argument that is propagated from R.
